title: Sunbla Khan
email: sunblakhan7589@gmail.com
description: Personal portfolio, blog, and contact hub of Sunbla Khan.
baseurl: ""
url: "https://sunblakhan.github.io"
markdown: kramdown
permalink: /blog/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: default

nav_pages:
  - title: About
    url: /aboutme/
  - title: Skills
    url: /skills/
  - title: Education
    url: /education/
  - title: Portfolio
    url: /projects/
  - title: Personality
    url: /personality/
  - title: Blog
    url: /blog/
  - title: Contact
    url: /contactme/
