title: "Sunbla Khan | Data Scientist & Software Engineer"
description: "Bridging Software Engineering and Data Science to build intelligent, automated solutions."
remote_theme: pages-themes/slate@v0.2.0

plugins:
  - jekyll-remote-theme

github_username: sunblakhan
show_downloads: false

# Navigation menu
header_pages:
  - aboutme.md
  - skills.md
  - projects.md
  - education.md
  - freelancing.md
  - personality.md
  - blog.md
  - contactme.md
