title: Sunbla Khan
email: sunblakhan7589@gmail.com
description: Personal portfolio, blog, and contact hub of Sunbla Khan.
baseurl: ""
url: "https://sunblakhan.github.io"
markdown: kramdown
permalink: /blog/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "_posts"
    values:
      layout: post

nav_pages:
  - title_en: About
    title_de: Über mich
    url: /aboutme/
  - title_en: Portfolio
    title_de: Portfolio
    url: /projects/
  - title_en: Personality
    title_de: Persönlichkeit
    url: /personality/
  - title_en: Blog
    title_de: Blog
    url: /blog/
  - title_en: Contact
    title_de: Kontakt
    url: /contactme/
